### ISSUE TITLE
model specification initial_concentrations not respected

### ISSUE THREAD

**Issue by jsnel** [glotaran/glotaran#131]
### Context
* glotaran version: 816b681
* Python version: 3.6.6
* Operating System: Jupyterlab on Linux

### Description

Observe the notebook: https://github.com/glotaran/glotaran-examples/blob/master/fluorescence/2001-Gobets_et_al-Streakdata_PSI/demo_notebook_ga_seq.ipynb

Run all cells, inspect the plots that show EAS and concentrations. 
The spectra shown there are actually DAS (as is evident from the shape and the concentrations which show parallel decay). 

The two model types differ in their specification as below, the rest is the same.
#### sequential model -> spectra = EAS
``` yaml
parameters:   
  - jvec:
    - [1, {vary: false}]
    - [0, {vary: false}]
    - [0, {vary: false}]
    - [0, {vary: false}]
   
k_matrices:
  - label: "km1"
    matrix: {
      '("s2","s1")': kinetic.1,
      '("s3","s2")': kinetic.2,
      '("s4","s3")': kinetic.3,
      '("s4","s4")': kinetic.4
    }
```
#### parallel model -> spectra = DAS
``` yaml
parameters:   
  - jvec:
    - [1, {vary: false}]
    - [1, {vary: false}]
    - [1, {vary: false}]
    - [1, {vary: false}]
   
k_matrices:
  - label: "km1"
    matrix: {
      '("s1","s1")': kinetic.1,
      '("s2","s2")': kinetic.2,
      '("s3","s3")': kinetic.3,
      '("s4","s4")': kinetic.4
    }
```
